import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import zlib from "zlib";

// Mermaid single-file UMD build, embedded into main.js so diagrams render fully
// offline inside the sandboxed srcdoc iframe (desktop + mobile). It is gzipped then
// base64-encoded (~1.3 MB vs ~3.5 MB raw) to keep main.js small enough to sync
// reliably (e.g. iCloud) and load on mobile. At runtime the plugin gunzips it
// (DecompressionStream) and injects it via a data: URI <script src> - base64 has no
// HTML-significant chars, so it sidesteps every parsing hazard of inlining raw JS
// (a "</script>", "<!--" or "$" in the minified source would break the <script>).
// Pinned vendored copy: vendor/mermaid.min.js (see vendor/README.md for version).
const MERMAID_SRC = fs.readFileSync("vendor/mermaid.min.js");
const MERMAID_GZ_B64 = zlib.gzipSync(MERMAID_SRC, { level: 9 }).toString("base64");

const builtins = [
	"_http_agent", "_http_client", "_http_common", "_http_incoming", "_http_outgoing",
	"_http_server", "_stream_duplex", "_stream_passthrough", "_stream_readable",
	"_stream_transform", "_stream_writable", "_tls_common", "_tls_wrap",
	"assert", "async_hooks", "buffer", "child_process", "cluster", "console",
	"constants", "crypto", "dgram", "diagnostics_channel", "dns", "domain",
	"events", "fs", "http", "http2", "https", "inspector", "module", "net",
	"os", "path", "perf_hooks", "process", "punycode", "querystring", "readline",
	"repl", "stream", "string_decoder", "timers", "tls", "trace_events",
	"tty", "url", "util", "v8", "vm", "worker_threads", "zlib",
];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	define: {
		MERMAID_GZ_B64: JSON.stringify(MERMAID_GZ_B64),
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
