import esbuild from "esbuild";
import process from "process";

const builtins = [
	"_http_agent", "_http_client", "_http_common", "_http_incoming", "_http_outgoing",
	"_http_server", "_stream_duplex", "_stream_passthrough", "_stream_readable",
	"_stream_transform", "_stream_writable", "_tls_common", "_tls_wrap",
	"assert", "async_hooks", "buffer", "child_process", "cluster", "console",
	"constants", "crypto", "dgram", "diagnostics_channel", "dns", "domain",
	"events", "fs", "http", "http2", "https", "inspector", "module", "net",
	"os", "path", "perf_hooks", "process", "punycode", "querystring", "readline",
	"repl", "stream", "string_decoder", "timers", "tls", "trace_events",
	"tty", "url", "util", "v8", "vm", "worker_threads", "zlib",
];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
