/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HTMLExperiencePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_HTML_EXPERIENCE = "html-experience-view";
var DEFAULT_SETTINGS = {
  enableScripts: true,
  sandboxPermissions: "allow-scripts allow-same-origin allow-forms allow-popups allow-modals",
  backgroundColor: "#ffffff",
  backgroundColorEnabled: false
};
var HTMLExperienceView = class extends import_obsidian.FileView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_HTML_EXPERIENCE;
  }
  getIcon() {
    return "code-glyph";
  }
  canAcceptExtension(extension) {
    return ["html", "htm"].includes(extension);
  }
  async onLoadFile(file) {
    this.contentEl.empty();
    const contents = await this.app.vault.readBinary(file);
    const decoder = new TextDecoder();
    const htmlStr = decoder.decode(contents);
    const mainView = this.contentEl.createDiv();
    mainView.setAttribute("style", "display: flex; flex-direction: column; height: 100%; padding: 0;");
    const sandbox = this.plugin.settings.enableScripts ? this.plugin.settings.sandboxPermissions : "allow-same-origin";
    const iframe = mainView.createEl("iframe", {
      cls: "html-experience-iframe",
      attr: { sandbox }
    });
    const baseHref = this.app.vault.getResourcePath(file);
    const doc = new DOMParser().parseFromString(htmlStr, "text/html");
    let baseElm = doc.querySelector("base");
    if (!baseElm) {
      baseElm = doc.createElement("base");
      doc.head.prepend(baseElm);
    }
    baseElm.setAttribute("href", baseHref);
    if (this.plugin.settings.backgroundColorEnabled) {
      const body = doc.querySelector("body");
      if (body) {
        body.style.backgroundColor = this.plugin.settings.backgroundColor;
      }
    }
    iframe.srcdoc = doc.documentElement.outerHTML;
  }
  canRenameExtension(extension) {
    return false;
  }
};
var HTMLExperienceSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "HTML Experience Settings" });
    new import_obsidian.Setting(containerEl).setName("Enable JavaScript").setDesc("Allow scripts to run in HTML files. Disable for untrusted content.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableScripts).onChange(async (value) => {
        this.plugin.settings.enableScripts = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sandbox permissions").setDesc("Space-separated list of iframe sandbox permissions.").addText(
      (text) => text.setPlaceholder("allow-scripts allow-same-origin...").setValue(this.plugin.settings.sandboxPermissions).onChange(async (value) => {
        this.plugin.settings.sandboxPermissions = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Background color").setDesc("Set a custom background color for HTML files.").addColorPicker(
      (picker) => picker.setValue(this.plugin.settings.backgroundColor).onChange(async (value) => {
        this.plugin.settings.backgroundColor = value;
        await this.plugin.saveSettings();
      })
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.backgroundColorEnabled).onChange(async (value) => {
        this.plugin.settings.backgroundColorEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Actions" });
    new import_obsidian.Setting(containerEl).setName("Reload active view").setDesc("Refresh the currently open HTML file to apply new settings.").addButton(
      (btn) => btn.setButtonText("Reload").onClick(async () => {
        this.plugin.reloadActiveView();
      })
    );
  }
};
var HTMLExperiencePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_HTML_EXPERIENCE, (leaf) => new HTMLExperienceView(leaf, this));
    this.registerExtensions(["html", "htm"], VIEW_TYPE_HTML_EXPERIENCE);
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile && ["html", "htm"].includes(file.extension)) {
          this.reloadViewsForFile(file);
        }
      })
    );
    this.addCommand({
      id: "reload-html-view",
      name: "Reload active HTML view",
      callback: () => this.reloadActiveView()
    });
    this.addSettingTab(new HTMLExperienceSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  reloadActiveView() {
    const activeView = this.app.workspace.getActiveViewOfType(HTMLExperienceView);
    if (activeView && activeView.file) {
      activeView.onLoadFile(activeView.file);
    }
  }
  reloadViewsForFile(file) {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_HTML_EXPERIENCE);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view.file && view.file.path === file.path) {
        view.onLoadFile(file);
      }
    }
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_HTML_EXPERIENCE);
  }
};
