/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HTMLExperiencePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_HTML_EXPERIENCE = "html-experience-view";
var HTMLExperienceView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.file = null;
    this.iframe = null;
  }
  getViewType() {
    return VIEW_TYPE_HTML_EXPERIENCE;
  }
  getDisplayText() {
    return this.file ? this.file.name : "HTML Experience";
  }
  getIcon() {
    return "code-glyph";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("html-experience-container");
    this.iframe = container.createEl("iframe", {
      cls: "html-experience-iframe",
      attr: {
        sandbox: "allow-scripts allow-same-origin allow-forms allow-popups",
        frameborder: "0"
      }
    });
    if (this.file) {
      await this.loadFile(this.file);
    }
  }
  async loadFile(file) {
    this.file = file;
    if (!this.iframe) return;
    const content = await this.app.vault.read(file);
    const blob = new Blob([content], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    this.iframe.src = url;
  }
  async onClose() {
    var _a;
    if ((_a = this.iframe) == null ? void 0 : _a.src) {
      URL.revokeObjectURL(this.iframe.src);
    }
  }
};
var HTMLExperiencePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerView(VIEW_TYPE_HTML_EXPERIENCE, (leaf) => new HTMLExperienceView(leaf));
    this.registerExtensions(["html", "htm"], VIEW_TYPE_HTML_EXPERIENCE);
    this.addCommand({
      id: "open-html-in-experience",
      name: "Open current file in HTML Experience",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile && (activeFile.extension === "html" || activeFile.extension === "htm")) {
          if (!checking) {
            this.openHTMLFile(activeFile);
          }
          return true;
        }
        return false;
      }
    });
  }
  async openHTMLFile(file) {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_HTML_EXPERIENCE);
    let leaf;
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = this.app.workspace.getLeaf("tab");
      await leaf.setViewState({
        type: VIEW_TYPE_HTML_EXPERIENCE,
        active: true
      });
    }
    const view = leaf.view;
    await view.loadFile(file);
    this.app.workspace.revealLeaf(leaf);
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_HTML_EXPERIENCE);
  }
};
